### ISSUE TITLE
cant setup the db part?

### ISSUE THREAD

**Issue by JTzLinux** [itflow-org/itflow-docker#5]
Hello everyone,

so I recently tried to set this up but I keep on getting this issue:
```
[Thu Nov 23 14:46:55.353561 2023] [php:error] [pid 34] [client HIDDEN:44748] PHP Fatal error:  Uncaught mysqli_sql_exception: No such file or directory in /var/www/html/setup.php:46\nStack trace:\n#0 /var/www/html/setup.php(46): mysqli_connect()\n#1 {main}\n  thrown in /var/www/html/setup.php on line 46, referer: https://HIDDEN/setup.php?database
HIDDEN - - [23/Nov/2023:14:46:55 +0000] "POST /setup.php?database HTTP/1.1" 500 185 "https://HIDDEN/setup.php?database" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
```
This is my compose file:
```
version: "3.9"
networks:
  nginx_default:
    external: true
      
  itflow-db:
    name: itflow-db
    external: false

volumes:
  itflow-db:

services:
  itflow:
    hostname: itflow
    container_name: itflow
    image: lued/itflow
    restart: unless-stopped
    depends_on: 
      - itflow-db
    networks:
      - nginx_default
      - itflow-db
    environment:
      - TZ=$TZ
      - ITFLOW_NAME=ITFlow
      - ITFLOW_URL=it.$ROOT_DOMAIN
      - ITFLOW_PORT=8080
      - ITFLOW_REPO=github.com/itflow-org/itflow
      - ITFLOW_REPO_BRANCH=master
      - ITFLOW_LOG_LEVEL=info
      - ITFLOW_DB_HOST=itflow-db
      - ITFLOW_DB_PASS=$ITFLOW_DB_PASS
    volumes:
      - ./itflow/:/var/www/html

  itflow-db:
    hostname: itflow-db
    container_name: itflow-db
    image: mariadb:10.6.11
    restart: always
    networks:
      - itflow-db
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=itflow
      - MARIADB_USER=itflow
      - MARIADB_PASSWORD=$ITFLOW_DB_PASS
    volumes:
      - itflow-db:/var/lib/mysql/
```
and the .env file is also present I dont know what to do
