### ISSUE TITLE
Docker image not containing itflow files

### ISSUE THREAD

**Issue by mohabgabber** [itflow-org/itflow-docker#9]
After setting up the docker compose file as follow:
```
networks:
  itflow-db:
    name: itflow-db

volumes:
  itflow-db:
  itflow-contents:

services:
  itflow:
    platform: linux/amd64
    hostname: itflow
    container_name: itflow
    image: itfloworg/itflow:latest
    restart: always
    depends_on: 
      - itflow-db
    networks:
      - itflow-db
    environment:
      - TZ=${TZ}
      - ITFLOW_NAME=${SITE_NAME}
      - ITFLOW_URL=${DOMAIN}
      - ITFLOW_PORT=8080
      - ITFLOW_REPO=github.com/itflow-org/itflow
      - ITFLOW_REPO_BRANCH=master
      - ITFLOW_LOG_LEVEL=info
      - ITFLOW_DB_HOST=${DB_HOST}
      - ITFLOW_DB_PASS=${DB_PASS}
    volumes:
      - itflow-contents:/var/www/localhost/htdocs

  itflow-db:
    image: mariadb:11.7.2-noble
    hostname: itflow-db
    container_name: itflow-db
    restart: always
    networks:
      - itflow-db
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    volumes:
      - itflow-db:/var/lib/mysql/
```

and opening the website i just get a page with the text "It Works!".

here's the container logs:

![Image](https://github.com/user-attachments/assets/c28650ba-d4ed-4982-93d1-aa9e5b25b4cb)

it can't clone the itflow files into /var/www/localhost/htdocs because there is a file there which is name "index.html". I had to delete it manually then restart the container in order for itflow to function normally.
